apiVersion: apps/v1
kind: Deployment 
metadata:
  name: skywalker-proxy
  labels:
    app: proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: proxy
  template:
    metadata:
      labels:
        app: proxy
    spec:
      volumes:
      - name: python-src-volume
        configMap:
          defaultMode: 420
          name: skywalker-codes-configmap
      - name: python-app-volume
        emptyDir: {}
      initContainers:
      - args:
        - base64 -d < /src/code > /tmp/func.decoded && unzip -o /tmp/func.decoded -d /app 
        command:
        - sh
        - -c
        image: skywalker/unzip:0.1
        name: codes-preparing
        volumeMounts:
        - mountPath: /app
          name: python-app-volume
        - mountPath: /src
          name: python-src-volume
      containers:
      - name: function
        image: skywalker/proxy:0.1
        ports:
          - containerPort: 5000
        env:
        - name: PYTHONPATH
          value: "/app"
        command: 
        - python
        - /app/web.py
        volumeMounts:
        - mountPath: /app
          name: python-app-volume
        envFrom:
        - secretRef:
            name: redis
